### ISSUE TITLE
Issues with various browsers

### ISSUE THREAD

**Issue by mtimms** [gooy/aurelia-animator-velocity#3]
Testing results on various browsers
1. Chrome on Windows - works as advertised
2. Chrome on Mac - works as advertised
3. Chrome on iPad - displays correctly, side links inoperable, no animations.
4. Safari on iPad - displays correctly, side links inoperable, no animations. 
5. Safari on Mac - displays correctly, side links inoperable, no animations.
6. IE11 on Windows - displays correctly, side links working, no animations.
7. Firefox on Windows - displays correctly, side links inoperable, animations work

**Comment by Aaike** [comment]
i've updated the demo , this should be the current state of things :
1. Chrome on Windows - works as advertised
2. Chrome on Mac - works as advertised
3. Chrome on iPad - displays correctly, side links working, page animations work but show unwanted flickering
4. Safari on iPad - works as advertised
5. Safari on Mac - works as advertised
6. IE11 on Windows - displays correctly, side links working, page animations not working due to https://github.com/aurelia/templating/issues/86
7. Firefox on Windows - displays correctly, side links working, page animations work but show unwanted flickering

I will first try to get all these issues resolved in this animator before i apply those fixes to the greensock and tinyanimate animators

**Comment by Aaike** [comment]
actually i tested IE11 again, and page animations seem to be working like in the other browsers , but it also suffers from unwanted flickering.

**Comment by mtimms** [comment]
Great stuff. Getting pretty close.

**Comment by Aaike** [comment]
This should be fixed now in the new release and demo, please give it a go ;)

Edit: some new issues have emerged that currently makes it fail on Safari and windows mobile , perhaps others. will have to to a round of browser testing ;)

**Comment by Aaike** [comment]
this has now been verified to work on :
- firefox and chrome on linux
- firefox, chrome and IE11, 360 secure browser on windows
- chrome on android
- chrome and safari on ipad
- safari, firefox , chrome for mac
- windows mobile IE11
